  pipeline {
    agent any
    environment {
      WORKER_IP = '3.110.197.181'
      DOCKERHUB_IMAGE = 'sachinpatkari/bookstore-app:latest'
    }
    stages {
      stage('Deploy to k8s') {
        steps {
          sh '''
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/sachin1_key.pem ubuntu@${WORKER_IP} "export KUBECONFIG=/home/ubuntu/kubeconfig && kubectl set image deployment/bookstore bookstore=${DOCKERHUB_IMAGE} --record"
          '''
        }
      }
      stage('Verify Deployment') {
        steps {
          sh '''
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/sachin1_key.pem ubuntu@${WORKER_IP} "export KUBECONFIG=/home/ubuntu/kubeconfig && kubectl rollout status deployment/bookstore"
          '''
        }
      }
    }
  }
